version: 2

jobs:
  apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Validate Terraform Formatting
          command: terraform fmt
          working_directory: product
      - run:
          name: Initialize Terraform
          command: terraform init
          working_directory: product
      - run:
          name: Plan Terraform
          command: terraform plan
          working_directory: product
      - run:
          name: Apply Terraform
          command: terraform apply --auto-approve
          working_directory: product

workflows:
  version: 2
  apply:
    jobs:
      - apply